name = "aetherclock-cron-worker"
main = "src/index.ts"
compatibility_date = "2026-06-01"

[[kv_namespaces]]
binding = "AETHERCLOCK_KV"
id = "dd42f5546b3645eb9131b8189b172bf5"

[triggers]
crons = ["* * * * *"]
